# Generated by Django 3.2.9 on 2021-11-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text1", models.CharField(max_length=20)),
                ("text2", models.CharField(max_length=20)),
                ("num1", models.IntegerField()),
            ],
        ),
    ]
