# Generated by Django 3.2.9 on 2022-02-17 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 677784)),
        ),
        migrations.AlterField(
            model_name='dump',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 689470)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 684340)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 683282)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 681550)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 680327)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 30, 43, 686311)),
        ),
    ]
