# Generated by Django 3.2.9 on 2021-11-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_buyerdata_quotationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationdata',
            name='abrv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.buyerdata'),
        ),
    ]
