# Generated by Django 3.2.9 on 2022-02-17 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20220218_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate_of_sku',
        ),
        migrations.AddField(
            model_name='item',
            name='dollor_rate',
            field=models.IntegerField(default=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 138187)),
        ),
        migrations.AlterField(
            model_name='dump',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 147157)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 142177)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 141180)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 140183)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 139186)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 3, 38, 17, 144171)),
        ),
    ]
