# Generated by Django 3.2.9 on 2022-02-21 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20220218_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcalculationdata',
            name='bottom_gsm',
            field=models.FloatField(default=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='dump',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 8, 6, 590185)),
        ),
    ]
