# Generated by Django 3.2.9 on 2022-01-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20220124_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 328489)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 333237)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 332245)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 331246)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 329245)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 29, 14, 334235)),
        ),
    ]
