# Generated by Django 3.2.9 on 2022-02-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20220221_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bottom_gsm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 664484)),
        ),
        migrations.AlterField(
            model_name='dump',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 668708)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 668708)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 667711)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 666548)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 665722)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 15, 34, 668708)),
        ),
    ]
