# Generated by Django 3.2.9 on 2022-01-25 05:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20220125_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 150112)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 152912)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 151918)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 151918)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 150916)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 59, 22, 153912)),
        ),
    ]
