# Generated by Django 3.2.9 on 2021-11-22 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_auto_20211122_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerdata",
            name="abrv",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="calculator.quotationdata",
            ),
        ),
    ]
