# Generated by Django 3.2.9 on 2022-02-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20220221_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 315924)),
        ),
        migrations.AlterField(
            model_name='dump',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 17, 21, 5, 316920)),
        ),
    ]
