# Generated by Django 3.2.9 on 2022-01-26 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20220125_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='item_1',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='calculator.Item'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 376671)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 378696)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 378696)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 377665)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 377665)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 13, 23, 52, 379693)),
        ),
    ]
