# Generated by Django 3.2.9 on 2021-11-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0006_quotationdata_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyerdata",
            name="abrv",
            field=models.CharField(max_length=50),
        ),
    ]
