# Generated by Django 3.2.9 on 2022-01-27 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_auto_20220126_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 501365)),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 506319)),
        ),
        migrations.AlterField(
            model_name='mastercarton',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 505322)),
        ),
        migrations.AlterField(
            model_name='productcalculationdata',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 504325)),
        ),
        migrations.AlterField(
            model_name='productdim',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 503322)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='items',
            field=models.ManyToManyField(blank=True, to='calculator.Item'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 15, 21, 57, 508313)),
        ),
    ]
